//This file is generated by ./target/cascadable.js

namespace MakerJs {

    export interface ICascade {
        $initial: any;
        $result: any;
        $reset: () => this;
    }

    export interface ICascadeModel extends ICascade {

    }

    export interface ICascadePath extends ICascade {

    }

    export interface ICascadePoint extends ICascade {

    }
}
